### ISSUE TITLE
Create a release process

### ISSUE THREAD

**Issue by Skarlso** [open-component-model/ocm#101]
**What would you like to be added**:

For a release process, we need consistent versioning implemented in code and in Markdown build file.

The process could do the following:
- [x] gather release notes from merged PRs
- [x]  designate an RC
- [x] release with the prefabricated release notes including which PRs this version contains
- [x] mark the generated binary with that specific version
- [x] Optionally, trigger a change in the website for any generated content updates
- [x] Optionally, create release docs
- [x] create the actual release in github with bundled up spec, manifests and binaries for all OS / ARCH combos.

Technical implementation is up to the picker of this ticket. I recommend using [GoReleaser](https://goreleaser.com/).

**Why is this needed**:

**Comment by Skarlso** [comment]
The following tasks might be performed on various repositories:

## Controllers

They already have set up containers and built images on a tag push. Extend this by creating artifacts and releases too. The release should contain that version's generated Manifest files as well.

## OCM

This repository lacks the complete release process. That includes creating images, doing version bumps and designating release docs.

**Comment by In-Ko** [comment]
As per our short discussion: We need to add to the release-process an automated way of updating the link to the latest official release, which is shown on our website.

**Comment by Skarlso** [comment]
We can use a parameterized workflow_dispatch in the target repo.
