### ISSUE TITLE
Announce Deprecation of schema version v3alpha1

### ISSUE THREAD

**Issue by morri-son** [open-component-model/ocm#1088]
**Description**
As a team we want to focus on simplicity and maintainability of our code base. Offering multiple (GA) versions of the serialization format for a component descriptor, even only as an option, raises complexity and therefore effort. We also did not see that version v3alpha1 has been accepted and really been used by the community. This is why we plan to continue with just the currently latest released version v2. v3alpha1 will be announced as deprecated. The deprecation date will be set to 2025-03-31.

The schema reference on the ocm website should only refer to v2. All examples, help texts, etc. on the website and in the OCM CLI should only refer to v2.

**Tasks**
- [ ] Announce deprecation in OCM Slack channels in SAP Slack and k8s Slack workspace

**Comment by maximilianbraun** [comment]
👌 🚀

**Comment by morri-son** [comment]
Announced in #open-component-model Slack channel in the K8s workspace: https://kubernetes.slack.com/archives/C05UWBE8R1D/p1732805125585759

**Comment by jakobmoellerdev** [comment]
We have extended the deprecation notice until EOY to accomodate our existing rework effort and give more time to switch
