### ISSUE TITLE
Digest Calculation for Filesystem Content

### ISSUE THREAD

**Issue by mandelsoft** [open-component-model/ocm#115]
Filesystem content may be provided in various technical formats: zip, tgz, tar,...

So far, the chosen archive format is taken in its binary form to calculate a digest.
It would be a good idea to have a format-agnostic digest for such content used for a dedicated FileSystemContent
Artifact type.

**What would you like to be added**:

Git already has solved this problem by introducing its Tree Hashes. So it seems to be useful to implement 
a compatible hashing for filesystem content based on the various archive formats.

It should be added a s a dedicated digest handler for the filesystem content artifact type.

**Why is this needed**:

This mechanism provides a format agnostic digest for file system content. It offers the possibility to repack content without loosing the validity of its digest used as part of the signing process.

**Comment by mandelsoft** [comment]
A package providing a Git-like treehash for filesystem or archive content and an incremental filetree compose is provided.
But it is not yet used anywhere.  
We have to establish DirectoryTree-like resources which should use such a digester.

**Comment by robertwol** [comment]
This is related to #42 
It has been decided to keep this issue on hold until it is necessary to implement

**Comment by morri-son** [comment]
implemented, but no real use-case so far.
