### ISSUE TITLE
Support comms channels for community help requests / discussions

### ISSUE THREAD

**Issue by nikimanoledaki** [open-component-model/ocm#124]
This is to create one or more channels for community folks to be able to ask for help or clarifying questions, feature requests, and talk directly with maintainers.

## `Help Request` issue templates
- [eksctl](https://github.com/weaveworks/eksctl/issues/new?assignees=&labels=kind%2Fhelp&template=request-for-help.md&title=%5BHelp%5D+)
- [kustomize](https://github.com/kubernetes-sigs/kustomize/issues/new?assignees=&labels=&template=question.md&title=%5BQuestion%5D)

## GitHub discussion boards

We already have something like this [here](https://github.com/open-component-model/ocm/discussions). We should add as many links as possible to redirect users to this board.
- [flux](https://github.com/fluxcd/flux2/issues/new/choose) redirects to [GitHub Discussions](https://github.com/fluxcd/flux2/discussions)
- [Kubernetes as well](https://github.com/kubernetes/kubernetes/issues/new/choose)

**Comment by ikhandamirov** [comment]
+ a public slack channel

**Comment by robertwol** [comment]
part of open-component-model/ocm-website#122

**Comment by robertwol** [comment]
Solved by https://github.com/open-component-model/ocm-website/issues/122
