### ISSUE TITLE
Add Security Policy

### ISSUE THREAD

**Issue by nikimanoledaki** [open-component-model/ocm#153]
This is to add a Security Policy for the OCM projects. This should be similar to [this SAP Securit Policy](https://github.com/gardener/documentation/blob/master/security-release-process.md) and [the Flux one](https://github.com/fluxcd/.github/blob/main/SECURITY.md).

**Comment by yitsushi** [comment]
Required details:
 - What is the private reporting email / medium?
 - List of members?

**Comment by In-Ko** [comment]
Security Policy added by this PR from @Shegox. Guess this solves this issue.
