### ISSUE TITLE
suppressed errors when closing session

### ISSUE THREAD

**Issue by jschicktanz** [open-component-model/ocm#160]
**What happened**:
I wanted to sign a component descriptor in a remote repository, where **pulling** the artefacts is public and therefore doesn't require authentication, however **pushing** the artefact does require authentication.

Pulling the artefact and local signing worked fine. However pushing the artefact failed with a 401 Unauthorized. This failed push operation was initially triggered by the call of `defer session.Close()` in the sign cmd (see: https://github.com/open-component-model/ocm/blob/main/cmds/ocm/commands/ocmcmds/common/cmds/signing/cmd.go#L76). The error that occured during `session.Close()` wasn't propagated back to the root level (the command should have failed, which it didn't).

I took a look into the other commands, and it seems that there is the same problem. Everytime an error is thrown during `session.Close()` the error is suppressed.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

**Comment by mandelsoft** [comment]
The error directly described is fixed with #167. It also provides a way how to handler deferred errors.
