### ISSUE TITLE
Extend examples with `transfer` using the library

### ISSUE THREAD

**Issue by Skarlso** [open-component-model/ocm#168]
**What would you like to be added**:

**Why is this needed**:

**Comment by jensh007** [comment]
Issue is about providing documentation to trigger transfers from Go code.
Starting point could be https://github.com/open-component-model/replication-controller/blob/main/pkg/ocm/ocm.go#L256

Related #186

**Comment by jensh007** [comment]
This should have been fixed with #385 and #386. Please reopen if this does not satisfy your needs.
