### ISSUE TITLE
[Feature parity] Make Lookup repository option available for all commands

### ISSUE THREAD

**Issue by Skarlso** [open-component-model/ocm#17]
`--lookup` should result in a Component Version Resolver that looks up component references and should be available for all commands.

This is available for most commands, but some are missing it. Identify which are these and apply the option to the command.

**Comment by jakobmoellerdev** [comment]
Still relevant in OCM v2. Propagating labels/annotations from the OCM component descriptor to OCI manifest metadata is not yet implemented in the v2 `bindings/go/oci` module.

**Maps to v2 epics:** open-component-model/ocm-project#837 (EPIC: OCI Artifact Input Type).
