### ISSUE TITLE
"OCM-ify" the OCM Toolset

### ISSUE THREAD

**Issue by In-Ko** [open-component-model/ocm#182]
**Description**
We have to deliver the OCM Tools using OCM mechanisms, therefore we need to create OCM Components for the tools.

Done Criteria
- [x] The OCM Toolset can be delivered via OCM itself
- [x] Multi-Platform Support is available

**Comment by jensh007** [comment]
PR [#312](https://github.com/open-component-model/ocm/pull/312) creates components as part of the release process

**Comment by jensh007** [comment]
REPO_ROOT for all published components is: https://github.com/orgs/open-component-model/packages
