### ISSUE TITLE
OCM CLI Documentation Issues/Feedback

### ISSUE THREAD

**Issue by In-Ko** [open-component-model/ocm#183]
**Description**
The OCM CLI documentation seems to have some smaller issues, which should be addressed:
- [x] OCM itself is designed to be independent of the underlying storage technology. Still, in some parts of the CLI documentation, terms like "registry" or "repository" are used, which are not meaningful in other storage backends than OCI registries. Example: https://ocm.software/docs/cli/download/artefacts/, where it is stated in the description "Download artefacts from an OCI registry."
- [x] The term "Gardener" is mentioned in one of the CLi documentation chapters (here: https://ocm.software/docs/cli/get/credentials/), which is not introduced, so it is not clear what "Gardener" means in this context.
- [x] The examples under https://ocm.software/docs/cli/transfer/artefacts/#examples do not match the command description ("transfer artefacts" is the command vs. "artefact transfer" is mentioned in the examples)
- [x] Docker and OCI is not 100% the same. Still, it is used in the CLI documentation interchangeably.
- [x] The CLI documentation writes "artefact", the Spec "artifact". We must be consistent here and use "artifact" everywhere.

**Comment by yitsushi** [comment]
> OCM itself is designed to be independent of the underlying storage technology. Still, in some parts of the CLI documentation, terms like "registry" or "repository" are used, which are not meaningful in other storage backends than OCI registries. Example: https://ocm.software/docs/cli/download/artefacts/, where it is stated in the description "Download artefacts from an OCI registry."

I understand the outlined issue, but I'm not sure how to resolved it. The CLI documentation does mention OCI and uses that in examples and other places because that's the only fully implemented storage backend in the CLI, alongside local directory/archive file. So yes, OCM itself is not bound to OCI, but the CLI is heavily depends on it.

**Comment by In-Ko** [comment]
Quick comment on this feedback:
> The CLI documentation writes "artefact", the Spec "artifact". We must be consistent here and use "artifact" everywhere.
We decided within the whole team to use artefact, so we will be consistent throughout the documentation and spec, but use british english spelling of the word, which is "artefact".

**Comment by yitsushi** [comment]
> Docker and OCI is not 100% the same. Still, it is used in the CLI documentation interchangeably.

@In-Ko: Can I ask for an example, I used ripgrep to find all `docker` references and it seems all places are correct and not a replacement of "oci".

Examples I found:
> OCI image/artefact reference following the possible docker schemes

> Additionally it provides some limited support for the docker daemon, OCI artefacts and

> The command-line-client can reuse docker credentials for authenticating against an OCI registry with a correspondig...

> kinds of technical artefacts (e.g. docker images, helm chart, binaries etc., git sources)

and some similar references, and they seem correct and not "used interchangeably".

**Comment by yitsushi** [comment]
> We will now use artifact everywhere (code, docu, website, ...)
> 
> Source: Slack

**Comment by In-Ko** [comment]
> Can I ask for an example, I used ripgrep to find all docker references and it seems all places are correct and not a replacement of "oci".

If you think the usage of docker is ok now everywhere, then thats enough, thanks!
