### ISSUE TITLE
[Gap closing][Feature Parity] Adding local files and resources to a component archive

### ISSUE THREAD

**Issue by Skarlso** [open-component-model/ocm#21]
**What would you like to be added**:

**Why is this needed**:

**Comment by In-Ko** [comment]
I guess this can be closed, right ? adding local resources is possible with OCM client, e.g. see here in this example: https://ocm.software/docs/guides/getting-started-with-ocm-flux/#adding-resources.

So if this is what you meant with this feature, we can close this task.

**Comment by Skarlso** [comment]
Yep. Thanks! :)
