### ISSUE TITLE
Implement Helm Chart Repo Access Method

### ISSUE THREAD

**Issue by In-Ko** [open-component-model/ocm#218]
**What would you like to be added**:
Similar to adding a [GitHub access method](https://github.com/open-component-model/ocm/issues/7) for GitHub Repositories, a specific [access method](https://github.com/open-component-model/ocm/blob/main/docs/ocm/model.md#artifact-access) for Helm Chart Repos should be provided.

**Why is this needed**:
Helm Charts are a widely used artifact type, which makes this a useful feature.

**Comment by jensh007** [comment]
Seems to be implemented with PR https://github.com/open-component-model/ocm/pull/354
