### ISSUE TITLE
Not all help options visible on ocm describe -h as per the documentation

### ISSUE THREAD

**Issue by mayankraipure12** [open-component-model/ocm#219]
**What happened**:
When run ocm in windows 
ocm describe -h
 ocm describe
ocm describe — Describe Artifacts

Synopsis:
  ocm describe [<options>] <sub-command> ...

Available Commands:
  artifacts   describe artifact version
  plugins     get plugins

Flags:
  -h, --help   help for describe

Description:
  Describe artifacts

**What you expected to happen**:
As per documentation on website:  https://ocm.software/docs/cli/describe/artifacts/

ocm describe artifacts [<options>] {<artifact-reference>}

  -h, --help            help for artifacts
      --layerfiles      list layer files
  -o, --output string   output mode (JSON, json, yaml)
      --repo string     repository name or spec

**How to reproduce it (as minimally and precisely as possible)**:
Follow the instructions on https://ocm.software/docs/guides/getting-started-with-ocm-flux/
and install ocm and run **ocm describe -h**

**Anything else we need to know**:
![image](https://user-images.githubusercontent.com/120610939/207844295-bd2ab11a-aa91-42bb-9928-12c7c384aa0d.png)

**Environment**:

**Comment by jensh007** [comment]
The behavior is intended, but perhaps not optimal. You get the missing parts by calling help on the sub-commands.
Try: 
```
ocm describe artifacts -h
```
or
```
ocm describe plugins -h 
```
Perhaps a hint should be added that there is additional documentation on subcommands available.

**Comment by In-Ko** [comment]
> Perhaps a hint should be added that there is additional documentation on subcommands available.

OK, then let's go with this: Add a hint to the help of the main command "ocm describe -h" like "Additional help is available per subcommand: ocm describe <subcommand> -h".
