### ISSUE TITLE
Make install doesn't work due to rfc date standard issue in make file

### ISSUE THREAD

**Issue by mayankraipure12** [open-component-model/ocm#226]
**What happened**:
worked on : ubuntu and windows but not on mac and alpine based images
**make install** fails due to date issue on alpine based docker images and mac due to not supported rfc-3339 for date 
**What you expected to happen**:
It should install ocm on inside the image .
**How to reproduce it (as minimally and precisely as possible)**:
docker file where I have checked 
check in Makefile line no 17 
** NOW         := $(shell date --rfc-3339=seconds | sed 's/ /T/')**
**Anything else we need to know**:
logs :
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/cespare/xxhash/v2 v2.1.2
go: downloading github.com/prometheus/procfs v0.7.3
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.4
date: unrecognized option: rfc-3339=seconds
BusyBox v1.35.0 (2022-11-19 10:13:10 UTC) multi-call binary.

Usage: date [OPTIONS] [+FMT] [[-s] TIME]

Display time (using +FMT), or set time

        -u              Work in UTC (don't convert to local time)
        [-s] TIME       Set time to TIME
        -d TIME         Display TIME, not 'now'
        -D FMT          FMT (strptime format) for -s/-d TIME conversion
        -r FILE         Display last modification time of FILE
        -R              Output RFC-2822 date
        -I[SPEC]        Output ISO-8601 date
                        SPEC=date (default), hours, minutes, seconds or ns

Recognized TIME formats:
        @seconds_since_1970
        hh:mm[:ss]
        [YYYY.]MM.DD-hh:mm[:ss]
        YYYY-MM-DD hh:mm[:ss]
        [[[[[YY]YY]MM]DD]hh]mm[.ss]
        'date TIME' form accepts MMDDhhmm[[YY]YY][.ss] instead
date: unrecognized option: rfc-3339=seconds
BusyBox v1.35.0 (2022-11-19 10:13:10 UTC) multi-call binary.

Usage: date [OPTIONS] [+FMT] [[-s] TIME]

Display time (using +FMT), or set time

        -u              Work in UTC (don't convert to local time)
        [-s] TIME       Set time to TIME
        -d TIME         Display TIME, not 'now'
        -D FMT          FMT (strptime format) for -s/-d TIME conversion
        -r FILE         Display last modification time of FILE
        -R              Output RFC-2822 date
        -I[SPEC]        Output ISO-8601 date
                        SPEC=date (default), hours, minutes, seconds or ns

Recognized TIME formats:
        @seconds_since_1970
        hh:mm[:ss]
        [YYYY.]MM.DD-hh:mm[:ss]
        YYYY-MM-DD hh:mm[:ss]
        [[[[[YY]YY]MM]DD]hh]mm[.ss]
        'date TIME' form accepts MMDDhhmm[[YY]YY][.ss] instead
^Cmake: *** [Makefile:68: install] Interrupt

/opt/ocm # make install > logs.txt
date: unrecognized option: rfc-3339=seconds
BusyBox v1.35.0 (2022-11-19 10:13:10 UTC) multi-call binary.

Usage: date [OPTIONS] [+FMT] [[-s] TIME]

Display time (using +FMT), or set time

        -u              Work in UTC (don't convert to local time)      
        [-s] TIME       Set time to TIME
        -d TIME         Display TIME, not 'now'
        -D FMT          FMT (strptime format) for -s/-d TIME conversion
        -r FILE         Display last modification time of FILE
        -R              Output RFC-2822 date
        -I[SPEC]        Output ISO-8601 date
                        SPEC=date (default), hours, minutes, seconds or ns

Recognized TIME formats:
        @seconds_since_1970
        hh:mm[:ss]
        [YYYY.]MM.DD-hh:mm[:ss]
        YYYY-MM-DD hh:mm[:ss]
        [[[[[YY]YY]MM]DD]hh]mm[.ss]
        'date TIME' form accepts MMDDhhmm[[YY]YY][.ss] instead
date: unrecognized option: rfc-3339=seconds
**Environment**:

**Comment by jensh007** [comment]
Can you please run `make install-requirements` in the root folder of the project and check if you have installed all pre-requisites?

**Comment by mayankraipure12** [comment]
Hi @jensh007 ,
Tried rinning,  make install-requirements, which leads to an error
screenshot attached.
![image](https://user-images.githubusercontent.com/120610939/209289444-6cac7f00-b2db-453c-be64-d3d441796845.png)

Thanks & Regards,
Mayank

**Comment by In-Ko** [comment]
We now have a nice build / release process, so to overcome the issues with "make install", you can now just download the latest CLI from the OCM-Repo under "releases". This should be solving your issue of getting the CLI installed.
