### ISSUE TITLE
Track GitOpsCon '23 & Open Source Summit

### ISSUE THREAD

**Issue by nikimanoledaki** [open-component-model/ocm#236]
This issue tracks the work for GitOpsCon '23. It was moved from KubeCon to Open Source Summit.

The North America edition will take place on May 8-9, 2023, in Vancouver, Canada.

https://events.linuxfoundation.org/cdcon-gitopscon/program/cfp/

**CFP Closes: Friday, February 10 at 11:59 PM PST**

**Comment by In-Ko** [comment]
Ingo to create a meeting for this week with the team.

**Comment by In-Ko** [comment]
All CFPs have been sent, so nothing else to do here from our side. Done and closed.

**Comment by In-Ko** [comment]
Both talks have been prepared and done, so this task can be closed now.
