### ISSUE TITLE
Update website when there is a new release

### ISSUE THREAD

**Issue by phoban01** [open-component-model/ocm#238]
**What would you like to be added**:
In order to do this we need to trigger a workflow on the website repository. This can be done by first of all creating a workflow in the `open-component-model/ocm` repository that is triggered for each new release. 

The workflow can use the repository-dispatch action the trigger a workflow on the website repository: https://github.com/peter-evans/repository-dispatch.

The details of updating the website should be the responsibility of the workflow running in the website repository.

Part of #101 

**Why is this needed**:
When there is a new ocm version released we should update the website accordingly.

**Comment by In-Ko** [comment]
As discussed this morning: We should update 2 places of the website: A release of the OCM repo (with CLI and Library) and a release of the OCM-SPEC repo (a new release of the spec itself).
