### ISSUE TITLE
Signature failure when verification is executed.

### ISSUE THREAD

**Issue by Skarlso** [open-component-model/ocm#264]
**What happened**:

Verification failed with outdated OCM CLI.

Error:

```
failed verifying signature of github.com/acme/podinfo:v1.0.0: github.com/acme/podinfo:v1.0.0: signature "RSASSA-PKCS1-V1_5" is invalid: signature verification failed, crypto/rsa: verification error
```

**What you expected to happen**:

Backwards compatibility with old signing versions.

**How to reproduce it (as minimally and precisely as possible)**:

Use an older version, for example `1470382629b76944f91974ff918b4b08b3a6f9ce`.
Sign your component with:
```
# Generate key
ocm create rsakeypair

# Sign
ocm sign component --signature alice --private-key rsa.priv --public-key rsa.pub ./component-archive
```

Switch to newer version like `e39625d6e919d33267da4778a1842670ce2bbf77`.

Then run verification with

```
ocm verify component -s alice -k rsa.pub --repo ghcr.io/skarlso github.com/acme/podinfo
```

The above error occurs.

**Anything else we need to know**:

**Environment**:

**Comment by Skarlso** [comment]
@mandelsoft hi! :)

So I think we figured out what happened, please confirm this.

So reading this line: https://github.com/open-component-model/ocm/pull/241/files#diff-e20820bdb6023e8ec7a7875c5d9e2574d30dd16d8c1b4f2d8ed0b8cf1f3700e9L37

Source was removed from the digest calculation. This means that the digest generated by the old version now mismatches the digest generated by the new version. This caused an error because of the digest mismatch that we had in the ocm-controller.

This error above I think comes from the fact that I used ocm verify which verified all of the versions in my component. And some of them had different keys being used.

**Comment by mandelsoft** [comment]
confirmed.
