### ISSUE TITLE
Add `ocm controller install` command that can install ocm-controller similar to `flux bootstrap`.

### ISSUE THREAD

**Issue by Skarlso** [open-component-model/ocm#266]
**What would you like to be added**:

The `flux bootstrap` and `flux install` commands are essential to an excellent user experience. If people already have `ocm` installed, they can run a simple command to bootstrap the controller.

The first iteration of this will be `ocm controller install` which just installs the controller and the CRDs. While the next iteration `ocm bootstrap` will install the manifests, the controller, the CRDs and will create an ocm component which will keep ocm-controller up-to-date.

**Why is this needed**:

**Comment by In-Ko** [comment]
As the pull request has been merged, we can close this issue, right @Skarlso  ?

**Comment by Skarlso** [comment]
We can. Or we can keep it as an epic. Either way I'll open a separate one for bootstrap command and the component version based approach.
