### ISSUE TITLE
flux bootstrap using local bare git repository using flux

### ISSUE THREAD

**Issue by mayankraipure12** [open-component-model/ocm#277]
**What happened**:
Create a local bare repository flux bootstrap git --url=/home/mayank/localrepo/mapping-with-cue.git  --path=./c
lusters/kind
✗ failed to create authentication options for /home/mayank/localrepo/mapping-with-cue.git: scheme "" is not supported
**What you expected to happen**:
Should reconcile flux with local git repo
**How to reproduce it (as minimally and precisely as possible)**:
Create a bare local reposiory
Create a application config using ocm
create remote as local
afte pushing the code , run flux bootstrap git --url "local repo path"
**Anything else we need to know**:

**Environment**:
local

**Comment by In-Ko** [comment]
Hi, flux can only be bootstrapped into a local GIT repo. The repo must exist in a central / remote location already. Check out https://docs.gitops.weave.works/docs/gitops-run/get-started/. Closing this issue.
