### ISSUE TITLE
Not Able to Sign the component

### ISSUE THREAD

**Issue by mayankraipure12** [open-component-model/ocm#284]
**What happened**:
While signing the component gives error
**What you expected to happen**:

ocm sign component --signature alice --private-key rsa.priv --public-key rsa.pub ./component-archive

applying to version "github.com/ujwaliyer/gardener-extension-provider-dns-infoblox:v0.1.1"...
  resource 0:  "name"="deployment": digest SHA-256:703dc3dbdd8227c5103e899a6da14294ff3fd5e956274801fa0b96bfd6f8bf6d[genericBlobDigest/v1]
  resource 1:  "name"="config": digest SHA-256:e2e48344b234e068c2d8fcc5e2fa162d488ffb4127d757f9a7fded8ca8b15fd6[genericBlobDigest/v1]
failed signing github.com/ujwaliyer/gardener-extension-provider-dns-infoblox:v0.1.1: github.com/ujwaliyer/gardener-extension-provider-dns-infoblox:v0.1.1: failed determining digest for resource image:v0.1.0 (OCI artifact ghcr.io/ujwaliyer/gardener-extension-provider-dns-infoblox:v0.1.0): cannot determine digest
finished with 1 error(s)
Error: signing: github.com/ujwaliyer/gardener-extension-provider-dns-infoblox:v0.1.1: failed determining digest for resource image:v0.1.0 (OCI artifact ghcr.io/ujwaliyer/gardener-extension-provider-dns-infoblox:v0.1.0): cannot determine digest

**How to reproduce it (as minimally and precisely as possible)**:
Download BTPRPC https://github.wdf.sap.corp/BTPRPC/ocm-infoblox/tree/new or clone the new branch for the repo ,
Try signing the component it will fail to do so.
**Anything else we need to know**:

**Environment**:

**Comment by jensh007** [comment]
Have you checked that the image ghcr.io/ujwaliyer/gardener-extension-provider-dns-infoblox actually exists? If I look at you packages at: https://github.com/ujwaliyer?tab=packages this seems to be empty. May be it is a private package. You could try making it public if authentication is an issue. You can check if ocm can access this image with
`ocm get artifact  <image-url>`

**Comment by ujwaliyer** [comment]
@mayankraipure12 , I removed the public Gardener infoblox-DNS package a while back as we have wrapped up the Infoblox project. You could try doing the same steps using some other project.

**Comment by mayankraipure12** [comment]
Issue got resolved
