### ISSUE TITLE
OCM helm resource deployment issue

### ISSUE THREAD

**Issue by mohammad-ammar14** [open-component-model/ocm#310]
**What happened**:
I have created OCM component with helm resource and tried to deployed using flux, I am able to get localized snapshot but its not deploying to the kind cluster.
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:
Please find the github link I tried: https://github.com/mohammad-ammar14/ocm-helm
**Environment**:

**Comment by Skarlso** [comment]
Because we don't support helm charts yet.

**Comment by Skarlso** [comment]
Okay, so the decision is to create a HelmRepository type object instead of an OCIRepository in case of a `helmChart` resource type.

**Comment by Skarlso** [comment]
This is now blocked on getting `CA` and `insecure-skip-tls` into upstream Helm then waiting for Flux to incorporate it.

After that, this pr: https://github.com/open-component-model/ocm-controller/pull/156 can progress further.

**Comment by mandelsoft** [comment]
With #354 access to helm repository is possible, also.
The resource type is still `helmChart`but the access method is different (`helmRepository`).

It is also possible to use the helm input type to take helm charts from a helm repository and put it directly into a component version as local artifact.
