### ISSUE TITLE
Provide documentation on resource types, input and access

### ISSUE THREAD

**Issue by jensh007** [open-component-model/ocm#316]
Enhance documentation on the various access and input types for resources. We have examples at various places but lack an overview and a systematic description:

- What is the difference between access and input types and when to use what
- Typical use case for each method/type
- Most important: Provide an example (ideally both on CLI level and programmatically with Go)
- Custom types

Even after working with this for weeks each time I need to create something I copy/paste a fragment from before and start from there
To me it seems this would help not only to get users up-to-speed but this is also in other means supportive:

- As a basis for integration tests (which should cover as many scenarios as possible)
- Maybe also in the VSCode-Plugin in the OCM creation wizard by providing a context-sensitive link from the input mask to the web site

**Comment by jensh007** [comment]
Added https://github.com/open-component-model/ocm-website/pull/85

**Comment by In-Ko** [comment]
So we can close this one, let's briefly discuss in our review meeting later.
