### ISSUE TITLE
Typo in https://github.com/open-component-model/ocm/tree/main/cmds/helminstaller#configuring-subcharts

### ISSUE THREAD

**Issue by dee0sap** [open-component-model/ocm#333]
**What happened**:

Text reads "are set ny preceeding"

**What you expected to happen**:

Text should read "are set by preceeding

**How to reproduce it (as minimally and precisely as possible)**:

Look here https://github.com/open-component-model/ocm/tree/main/cmds/helminstaller#configuring-subcharts

**Anything else we need to know**:

**Environment**:

**Comment by jensh007** [comment]
Fixed with PR #374
