### ISSUE TITLE
Integrate an option for keyless signing

### ISSUE THREAD

**Issue by vasu1124** [open-component-model/ocm#335]
**What would you like to be added**:
Please evaluate and integrate a keyless signing process like cosign into ocm.
https://www.youtube.com/watch?v=d5vROySf1I8

**Why is this needed**:
Let's Encrypt has simplified the ease of consumption and life cyclemanagement for web certificates.
Similarly, sigstore.dev with the help of OpenSSF and the supply chain momentum will simplify the code signing process.

The value proposition is undeniable.

OCM should support and contribute to the emerging standard around Sigstore and offer a simple code signing experience.

**Comment by vasu1124** [comment]
https://eprint.iacr.org/2023/003.pdf (thanks @phoban01 and @mandelsoft)

This paper alleges that the cryptographic protocol behind sigstore has no merit.

sigstore.dev responded with https://blog.sigstore.dev/why-you-cant-use-sigstore-without-sigstore-de1ed745f6fc/

While the value/marketing proposition of integrating OCM with Sigstore still holds true, we can reduce the priority of this request until we have clear guidance.

**Comment by phoban01** [comment]
I think there are still strong benefits in enabling these kinds of workflows for ocm.
