### ISSUE TITLE
ocm should fail when transfer to remote repo is skipped because it already exists.

### ISSUE THREAD

**Issue by jensh007** [open-component-model/ocm#387]
**What happened**:
Try pushing with a component that already exists:
```
ocm transfer ctf gen/ctf ghcr.io/jensh007/ocm   
transferring component "ocm.software/ocmcli-image"...
  transferring version "ocm.software/ocmcli-image:0.3.0-rc.2"...
    version "ocm.software/ocmcli-image:0.3.0-rc.2" already present -> skip transport
...
echo $?                                         
0
```

**What you expected to happen**:
exit code should be non zero

Note that the option `-f` is not set. Currently you have to look at stdout to see that it was skipped.

**How to reproduce it (as minimally and precisely as possible)**:
see above

**Anything else we need to know**:
I detected this when executing a github action that succeeds and you don’t have any clue that it actually did not do anything.
When someone really needs the current behavior I would prefer adding another option like `--ignore-failure-on-exist` or something. It probably comes from the fact that some components before might already have been pushed and the question arises then whether to continue with the remaining ones or abort. 

**Environment**:
ocm version 0.3.0-dev+4b053e6ddd15485b58e9808c3cf33a5034cff541

**Comment by mandelsoft** [comment]
@jensh007  Why should there an error code? If you have a complex CV structure it is a common scenario to transport sub closed sub graphs.
If there is a common part among multiple such sub graphs, the transport should not fail, if a shared CV is already present at the target.

Maybe, there could be an explicit  option used to cause a failure in such a case. But the standard behaviour should be kept as it is.

**Comment by jensh007** [comment]
We had a slack discussion on this. Background:

I am just wondering and find the behavior of the OCM CLI confusing. As you know, you can overwrite existing versions when pushing using the -f or --overwrite flags. But if you do not set this flag it currently ignores the push and indicates this only on stdout (“-> skip transport”). IMHO it should fail in such a case:

```
ocm transfer ctf gen/ctf ghcr.io/jensh007/ocm   
transferring component "ocm.software/ocmcli-image"...
  transferring version "ocm.software/ocmcli-image:0.3.0-rc.2"...
    version "ocm.software/ocmcli-image:0.3.0-rc.2" already present -> skip transport
...
echo $?                                         
0
```
I detected this when executing a github action that succeeds and **you don’t have any clue that it actually did not do anything.**
When someone really needs the current behavior I would prefer adding another option like --ignore-failure-on-exist or something.
It probably comes from the fact that some components before might already have been pushed and the question arises then whether to continue with the remaining ones or abort. There are no transactions… :exploding_head:
What do you think? Should we create an issue for this?

**Comment by jensh007** [comment]
Of course you should keep track of what was already pushed and not fail if the component appears again.

**Comment by mandelsoft** [comment]
I'll add add a check, whether the existing cv is equal to the one to be transported. If there is a relevant delta
the operation will provide an error.

**Comment by jensh007** [comment]
Tested and works.
