### ISSUE TITLE
Fix OSPO-related issues in OCM Repos

### ISSUE THREAD

**Issue by In-Ko** [open-component-model/ocm#391]
**Description**
There is a certain process we have to follow to be compliant with e.g the REUSE Tool. Over the past few days / weeks, some new repos have been created or former private ones have been set to public. This lead to quite some issues reported by the respective Bot, here's the filter: https://github.com/issues?q=is%3Aissue+org%3Aopen-component-model+archived%3Afalse+is%3Aopen+author%3Asap-ospo-bot+

We should fix those by following our agreed process for new repos.

**Comment by jensh007** [comment]
Fixed https://github.com/open-component-model/ocm-integrationtest/issues/7

**Comment by jensh007** [comment]
Fixed, PRs need to be merged.
