### ISSUE TITLE
Workshop to detail-out "Simplification / Ease-of-use" Epic

### ISSUE THREAD

**Issue by In-Ko** [open-component-model/ocm#393]
**Description**
We need the whole team to gather-up and brainstorm about the various areas in which we have to simplify OCM and improve the "ease-of-use".

Workshop will be virtual. Outcome of the workshop must be enough details and a clear priority of everything the team will invest in regarding the Epic (https://github.com/open-component-model/ocm/issues/390). A first start is already maintained in the Epic, which has to be updated after the workshop.

**Comment by robertwol** [comment]
The workshop was conducted which lead to a series of actions items documented in epic #390
