### ISSUE TITLE
Helm chart downloader doens't return the chart name it downloaded

### ISSUE THREAD

**Issue by Skarlso** [open-component-model/ocm#509]
**What happened**:

This section under `pkg/contexts/ocm/download/handlers/helm/handler.go`:

```go
	_, _, err = download(p, art, path, fs)
	if err != nil {
		return true, "", err
	}
	return true, "", nil
```

Should return the value returned by `download` which is the name it eventually created the file with.

**Comment by Skarlso** [comment]
Oh it already does on latest. It's just not release apparently.

**Comment by robertwol** [comment]
@Skarlso 
New release was created v0.4.0 was released: https://github.com/open-component-model/ocm/releases/tag/v0.4.0
please check if this is still the case and close/update the ticket.

**Comment by Skarlso** [comment]
Works now, thanks.
