### ISSUE TITLE
Support for feeding RBSC

### ISSUE THREAD

**Issue by mandelsoft** [open-component-model/ocm#518]
To support the inbound process for SAPs delivery channel (RBSC=repository based shipment channel) we need two basic extensions of the OCM command line tool:
- provide a check command to check whether a complete component version graph has been imported per value transport.
   It must check whether along the component version references only local access methods are used.

(Already implemented:)
- the transfer command must be able to write a yaml/json file describing all the component versions, which have been transported
(with the --recursive) options. This will be requested by a new option allowing to specify the bom output file.

**Comment by robertwol** [comment]
@ccwienk @ikhandamirov 
Could you confirm if this will be required for the RBSC work you doing and/or if you can provide additional specific requirements for OCM.

**Comment by ikhandamirov** [comment]
@mandelsoft , do I understand correctly that the completeness check actually checks two things:
1. That all referenced components are available in the given repository
2. That all referenced external resources are present as local blobs
