### ISSUE TITLE
Stop replacing cobra package with a user owned fork

### ISSUE THREAD

**Issue by Skarlso** [open-component-model/ocm#53]
This `replace` statement in the `go.mod` file:

```
replace github.com/spf13/cobra => github.com/mandelsoft/cobra v1.4.1-0.20220807114430-d47656a53e96
```

...should be removed. The required feature should either be worked out differently or used differently.
This fork belongs to a user instead of the community behind cobra, which constantly updates the package and applies security fixes. This package is already 17 commits behind at the time of this writing, including a fix [here](https://github.com/spf13/cobra/pull/1612) which appears to have fixed the reason why the fork exists.

**Comment by yitsushi** [comment]
Any progress on this one?

**Comment by Skarlso** [comment]
Uwe added more context and information to his PR. It's awaiting Review. I pinged Marc.

**Comment by ikhandamirov** [comment]
Hi @Skarlso, Marc is not very responsive in the recent months. Maybe for a good reason. Is there a different possibility to bring it to attention of VMware?

**Comment by Skarlso** [comment]
It's the contributors / maintainers of cobra that needs to be made aware and not VMware. :)

**Comment by ikhandamirov** [comment]
@Skarlso you are right, of course. But the question remains, if there is somebody else to ping.

**Comment by Skarlso** [comment]
I don't know sadly. Look through the contributors and who is the most active one and ping them. 😊

**Comment by ikhandamirov** [comment]
@Skarlso This is exactly the reply I was afraid of. :) I was hoping for personal connection of you, which could be magically activated. :)
