### ISSUE TITLE
Implement additional credential repository for Hashicorp's Vault

### ISSUE THREAD

**Issue by robertwol** [open-component-model/ocm#540]
**What would you like to be added**:
This issue is about extending the current set of credential repositories with one for Hashicorp's Vault. 

> ❗ Other secret stores to be considered (e.g. Azure Key Vault as teams often use Azure DevOps for their pipelines)

**Why is this needed**:
This allow to reference credentials located within Vault.

The OCM library provides an own mechanism to provide credentials to be accessed by OCM extensions.

Therefore, an own Context type **credentials** is used. Like the other context types (and the OCM content type)
it can be extended, in this case we require a new **credential repository type**. So far, there is the dockerconfig repo type. What would have to be done is to implement a new kind of credential repository providing access to credentials stored in Vault.

The credentials provisioning in the OCM lib then consist of four parts:

- credential repositories
a credential repository is an abstraction for a set of named credential sets (for example username and password).
- the notion of a consumer identity
This is just a set of attributes plus a type attribute. Every kind of consumer, for example an OCI registry, or a GitHub repository defines an on type key and a set of properties defining the concrete environment credentials should be used for (for example, the GitHub server URL and the GitHub Repository, or the OCI registry URL and a repository path prefix, etc)
- a configurable credential mapping, which maps consumer ids to credential sets in credential repositories.
- Potentially type specific consumer matchers.
It matches a given credential request, consisting of the consumer id for a dedicated technical environment against the configured credential mappings. The best matching mapping is used to get the credentials from the mapped credential set. For example this matching might just be a one to one matching of the consumer attributes, or more complex. For example to match a given repository path in the request by a path prefix given in the credential mapping.

A piece of code requiring credentials for a dedicated environment then composes the consumer id for this environment according to the rules for the dedicated type of environment (for example OCI or GitHub) and asks the credential context to provide credentials for this id. Here, the mappings are matched and the credentials are taken from the found credential set (in the mapped **credentials repository**).

Via configuration the credential context can be configured in a generic manner to know various credential repositories and dedicated consumer id mapping.

**Comment by morri-son** [comment]
I updated the description with the explanation given by @mandelsoft
