### ISSUE TITLE
Signing: support for organization validated public key certificates delivered together with the signature.

### ISSUE THREAD

**Issue by mandelsoft** [open-component-model/ocm#584]
**What would you like to be added**:

Using the signing server, the provided signatures contains the public key as part of a certificate chain.
Here at SAP this will be based on an officially provided organization validated certificate. The allows
to change the public key every ew weeks. 

So far, the identity for the signature validation is based on the public key provided during  verification.
With the above feature, the public key can be taken from the signature after validating the cert chain.
Additionally the identity of the signature (in OCM ever signature has a name) must be validated against
the Distinguished Name (DN) of the trusted public key certificate.

This has extensively discussed in the past week with Christian Cwienk,  Final Assembly (Torsten Stephan and Stefan Gabriel)
 and our Security group. The result will be a process similar to the signing of Java artifacts.

Therefore, the signing procedure has to slightly changed:
- during signing: If the signing is based on a certificate chain based public key, it has
  - to be validated and the signature name must be validated against the DN.
  - the signature has always to be stored together with the certificate chain.
- during verification: the verification not necessarily requires a public key. 
  - if no key is given, the validation must be based on a validated cert chain provided with the signature.
  - the above checks must be done to match the DN against the verified signature name.

**Why is this needed**:

- To support SAP's way to provide and validate signatures for its deliveries.
- To provide a verification able to deal with changing public keys.

**Comment by robertwol** [comment]
for reference:

Many regulated Private and Restricted Clouds including GOVs and DoDs require FedRamp mandatory compliance, especially control CM-14 

**Control Identifier**: CM-4
**Control Name:** Signed Components
**Control text:** Prevent the installation of [Assignment: organization-defined software and firmware components] without verification that the component has been digitally signed using a certificate that is recognized and approved by the organization.
**Discussion:** Software and firmware components prevented from installation unless signed with recognized and approved certificates include software and firmware version updates, patches, service packs, device drivers, and basic input/output system updates. Organizations can identify applicable software and firmware components by type, by specific items, or a combination of both. Digital signatures and organizational verification of such signatures is a method of code authentication.

https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final
