### ISSUE TITLE
Using --input to add resources on Windows causes yaml error 

### ISSUE THREAD

**Issue by markrexwinkel** [open-component-model/ocm#648]
**What happened**:

When adding a Helm Chart resource to component archive using --input arguments, a error occurs:
```
processing resource (by options)...
Error: resource (by options): yaml: found unknown escape character
```

**What you expected to happen**:

The resource should be added to the component archive without errors.

**How to reproduce it (as minimally and precisely as possible)**:

Assuming you are in a directory: `E:\t\bugrepo`

```PowerShell
# Create component archive
ocm create ca --file ca --scheme ocm.software/v3alpha1 --provider test.com test.com/test 1.0.0

# Pull Helm chart (normally this will be a Helm chart that is build in a pipeline
helm pull oci://registry-1.docker.io/bitnamicharts/postgresql --version 14.0.5

# Add resource (notice the full path here, because that is causing the issue)
ocm add resources --file ca --name postgresql --type helmChart --inputType helm --inputPath E:\t\bugrepo\postgresql-14.0.5.tgz --inputVersion 14.0.5
```

**Anything else we need to know**:
The problem is the full path for the --inputPath argument. What happens:
* ocm creates a json representation of the input variables
* ocm runs the templater over this json, by default this is the subst templater, this templater is also used when specifying none)
* the subst templater removes the backslash escaping from the json causing the error
* the templater is applied at [line 57: https://github.com/open-component-model/ocm/blob/main/cmds/ocm/commands/ocmcmds/common/addhdlrs/utils.go](https://github.com/open-component-model/ocm/blob/main/cmds/ocm/commands/ocmcmds/common/addhdlrs/utils.go)

You can workaround this error if you use double backslashes: ` --inputPath E:\\t\\bugrepo\\postgresql-14.0.5.tgz`. This will lead to another error which I will describe in another issue.

**Environment**:

OS: Windows 11 Pro 23H2
ocm: v0.6.0

**Comment by erwinkersten** [comment]
linking to the 'another issue' : #649 Adding local resource that is not on the same drive as the temp directory causes error (Windows)
