### ISSUE TITLE
Missing flags in cmd "ocm componentarchive transfer"

### ISSUE THREAD

**Issue by jschicktanz** [open-component-model/ocm#66]
**What happened**:
I executed `ocm componentarchive transfer --help` and expected various cmd flags to appear (e.g. closure option, lookup option (see #65), ...). However I got the following output:

```
ocm componentarchive transfer — Transfer Component Archive To Some Component Repository

Synopsis:
  ocm componentarchive transfer [<options>]  <source> <target>

Flags:
  -h, --help          help for transfer
  -t, --type string   archive format (default "directory")

Description:

  Transfer a component archive to some component repository. This might
  be a CTF Archive or a regular repository.
  If the type CTF is specified the target must already exist, if CTF flavor
  is specified it will be created if it does not exist.

  Besides those explicitly known types a complete repository spec might be configured,
  either via inline argument or command configuration file and name.

  The «--type» option accepts a file format for the
  target archive to use. The following formats are supported:
  - directory
  - tar
  - tgz
  The default format is «directory».
```

**What you expected to happen**:
Expected various cmd flags to appear (e.g. closure option, lookup option (see #65), ...)

**How to reproduce it (as minimally and precisely as possible)**:
Execute `ocm componentarchive transfer --help`

**Anything else we need to know**:

**Environment**:

**Comment by jmickey** [comment]
Hi @jschicktanz, 

It looks like #65 the flags were added the `ocm transfer` command, not the `ocm componentarchive transfer` command. So rather than being a bug, the options simply don't exist on the command.

Should I add them?

**Comment by ikhandamirov** [comment]
Hi @jmickey, #65 was provided as an example of the expected output.
I'm not sure, if Johannes is available. @jensh007, @mandelsoft, could you please check the question and come back to Josh.

**Comment by jensh007** [comment]
Checked the mentioned command and the list of flags is complete. Seems to have been fixed.
