### ISSUE TITLE
npm support does not work with nexus

### ISSUE THREAD

**Issue by jensh007** [open-component-model/ocm#769]
**What happened**:
npm artifact type does not work with nexus

**What you expected to happen**:
npm resources should work with any npm repository

**How to reproduce it (as minimally and precisely as possible)**:
```
15:31:38  debug sapOcmCreateComponent - components:
15:31:38  debug sapOcmCreateComponent - - name: github.wdf.sap.corp/open-component-model/npm-ocm
15:31:38  debug sapOcmCreateComponent -   version: ...15:31:38  debug sapOcmCreateComponent -   resources:
15:31:38  debug sapOcmCreateComponent -   - name: npmpackage
15:31:38  debug sapOcmCreateComponent -     type: npmPackage
15:31:38  debug sapOcmCreateComponent -     version: ...
15:31:38  debug sapOcmCreateComponent -     access:
15:31:38  debug sapOcmCreateComponent -       type: npm
15:31:38  debug sapOcmCreateComponent -       registry: https://staging.repositories..../stage/repository/...
15:31:38  debug sapOcmCreateComponent -       package: npm-ocm
15:31:38  debug sapOcmCreateComponent -       version: ...
```
OCM CLI generates a 404 error.
It is not an ocm issue. It is a nexus issue. You can do the same with curl:
curl -u ***:*** https://staging.repositories.../stage/repository/.../npm-ocm/0.1.0-...                   
{"success":false,"error":"Package 'npm-ocm-0.1.0-...' not found"}

The problematic call is:  https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md#getpackageversion 
The issue is documented here:  https://github.com/sonatype/nexus-public/issues/224

Is there any possibility to workaround this limitation?

**Anything else we need to know**:

**Environment**:

**Comment by morri-son** [comment]
adding @hilmarf for awareness
