### ISSUE TITLE
Link to integration test report does not work

### ISSUE THREAD

**Issue by morri-son** [open-component-model/ocm#835]
In line 5 of the README.md there is a link to the integration tests: https://open-component-model.github.io/ocm-integrationtest/report.html. This does not work, although the reports are available under a dedicated URL per report, e.g. https://open-component-model.github.io/ocm-integrationtest/report-8eec36386c79fdaaa04b67b973f3c996e9c08627.html

https://github.com/open-component-model/ocm/blob/main/README.md?plain=1#L5

This should get fixed.

**Comment by morri-son** [comment]
already fixed

**Comment by hilmarf** [comment]
fixed by https://github.com/open-component-model/ocm/pull/871
