### ISSUE TITLE
Github Action: Release build step "cache go-build and mod" writes tons of errors

### ISSUE THREAD

**Issue by morri-son** [open-component-model/ocm#847]
**What happened**:
The GitHub action steps writes tons of errors like 

```
/usr/bin/tar: ../../../go/pkg/mod/go.starlark.net@v0.0.0-20231121155337-90ade8b19d09/starlark/testdata/while.star: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/go.starlark.net@v0.0.0-20231121155337-90ade8b19d09/starlark/testdata/function_param.star: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/go.starlark.net@v0.0.0-20231121155337-90ade8b19d09/starlark/example_test.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/go.starlark.net@v0.0.0-20231121155337-90ade8b19d09/starlark/int_test.go: Cannot open: File exists
```

writes a huuuuuuge log and and takes quite long, nonetheless is successful.

**What you expected to happen**:
no errors occur

**How to reproduce it (as minimally and precisely as possible)**:
check https://github.com/open-component-model/ocm/actions/runs/9446619572/job/26017119898 and trigger the action again.

**Comment by morri-son** [comment]
@mandelsoft and @fabianburth , can you please check this? Maybe we sync files twice or the cleanup of the runner FS at the end does not work like expected?

**Comment by hilmarf** [comment]
Why do we have the additional `cache` step anyway? The regular `setup-go` has already a [caching mechanism integrated](https://github.com/actions/setup-go?tab=readme-ov-file#caching-dependency-files-and-build-outputs), which is normally active by default...

**Comment by morri-son** [comment]
> Why do we have the additional `cache` step anyway? The regular `setup-go` has already a [caching mechanism integrated](https://github.com/actions/setup-go?tab=readme-ov-file#caching-dependency-files-and-build-outputs), which is normally active by default...

@mandelsoft can you please comment?
