### ISSUE TITLE
Add upload to all package managers mentioned in the Installation Guide to the GitHub action "Release" 

### ISSUE THREAD

**Issue by morri-son** [open-component-model/ocm#856]
**What would you like to be added**:
All mentioned installation possibilities from README.md https://github.com/open-component-model/ocm/blob/main/README.md should be added to the release action, so that with every release all packages in the different package managers get updated automatically.

Like mentioned in #855, skript and credential are already available. Please reach out to @ccwienk 

**related**
- https://github.com/open-component-model/ocm/issues/818

**Comment by hilmarf** [comment]
AUR + Chocolatey update - https://github.com/open-component-model/ocm/pull/897

**Comment by hilmarf** [comment]
https://github.com/microsoft/winget-pkgs/pull/175451
