### ISSUE TITLE
`date` command in build process breaks on OSX

### ISSUE THREAD

**Issue by Skarlso** [open-component-model/ocm#9]
**What happened**:

```
make build
date: illegal option -- -
usage: date [-jnRu] [-r seconds|file] [-v[+|-]val[ymwdHMS]]
            [-I[date | hours | minutes | seconds]]
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
go build -ldflags "-s -w \
                -X github.com/open-component-model/ocm/pkg/version.gitVersion=0.1.0+fbda49d967d8607f658cb5b4b6c3b1c653826004 \
                -X github.com/open-component-model/ocm/pkg/version.gitTreeState=dirty \
                -X github.com/open-component-model/ocm/pkg/version.gitCommit=fbda49d967d8607f658cb5b4b6c3b1c653826004 \
                -X github.com/open-component-model/ocm/pkg/version.buildDate=" \
                ./cmds/ocm
```

Mode detailed:

```Makefile
		-X github.com/open-component-model/ocm/pkg/version.buildDate=$(shell date --rfc-3339=seconds | sed 's/ /T/')" \
```

On OSX the default `date` doesn't have --rfc-3339 option.

```
date --rfc-3339=seconds | sed 's/ /T/'
date: illegal option -- -
usage: date [-jnRu] [-r seconds|file] [-v[+|-]val[ymwdHMS]]
            [-I[date | hours | minutes | seconds]]
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
```

Incidentally, the OSX date is more easy to format actually, because it doesn't omit the `T` and is a more simple format like this:

```
date -Iseconds
```

Which will produce the same output as the above GNU date.

**What you expected to happen**:

The build to succeed.

**How to reproduce it (as minimally and precisely as possible)**:

Run `make build` on OSX.

**Anything else we need to know**:

Just add a switch on OS to use a different date command.

**Environment**:

OSX.

**Comment by jakobmoellerdev** [comment]
Still relevant in OCM v2. The v2 plugin system (`bindings/go/plugin`) and descriptor extensions are dynamic — JSON schemas for inputs, access specs, and repo specs would significantly improve editor support.

**Maps to v2 epics:** open-component-model/ocm-project#1086 (Create ADR for CLI plugins support/integration), open-component-model/ocm-project#1001 (EPIC: CLI command plugin capability).
