### ISSUE TITLE
OCM-CLI should prefer digest-tag for "mixed" OCI-Artefact-Tags

### ISSUE THREAD

**Issue by ccwienk** [open-component-model/ocm#911]
Widely-spread OCI-Runtimes, such as dockerd, or containerd allow usage of "mixed" OCI-Artefact-tags (tag + digest -  `<repository>:<tag>@<digest>`). Such tags are interpreted as digest-tags (i.e. symbolic tag is ignored). Motivation for using such "mixed" tags is to keep human-friendly tags, while still benefit from content-addressing.

When replicating OCM-Components w/ OCI-Artefacts w/ such tags (`ocm transfer`), OCM-CLI seems to prefer symbolic tag, and ignore digest, which consequently breaks if "mixed-tags" are converted to just digest-tags in an "out-of-bands"-replication-process.

Hence, I suggest to change OCM-CLI's behaviour like so:

If resource-access's imageReference attribute contains "mixed tag":
- digest-tag should be honoured for _retrieving_ the artefact (ocm-cli should drop symbolic part for retrieval)
- mixed-tag should be retained for re-upload

It might be a good idea to make the latter behaviour configurable, as there might be target-oci-registries that will not accept mixed-tags. Genereally-speaking, conversion of tags between symbolic <-> mixed <-> digest might be offered as an option for `ocm transfer` cmd. Might also be covered via  #902 .

**Comment by Skarlso** [comment]
Be advised that there is a massive refactor of the container handling layer for OCI.

https://github.com/open-component-model/ocm/pull/904

Any change that is required for this, should be added after this change lands. That said, is it possible that this is a no-op with the proposed change to ORAS?

**Comment by ccwienk** [comment]
well, currently this is a bug from my pov, which we had to create a workaround for.

**Comment by Skarlso** [comment]
Yeah, hopefully the PR will be merged soon.... Just a final review needed. 🤞

**Comment by morri-son** [comment]
bug or missing feature, anyway :-) We plan to pick this up in the next sprint, starting 6th Oct.

**Comment by fabianburth** [comment]
I just want to mention here that with `<repository>:<tag>@<digest>`, the tag is completely ignored by common tooling (such as docker or podman). So, the image will be successfully fetched even though the tag may not exist.

**Comment by morri-son** [comment]
> I just want to mention here that with `<repository>:<tag>@<digest>`, the tag is completely ignored by common tooling (such as docker or podman). So, the image will be successfully fetched even though the tag may not exist.
Since the tooling will still use the digest to pull the (correct) image, I guess this is ok, isn't?

**Comment by mandelsoft** [comment]
yes, there is coding preferring the tag, this has to be fixed.
