### ISSUE TITLE
Provide `arm64` ocm-cli image

### ISSUE THREAD

**Issue by zkdev** [open-component-model/ocm#947]
**What would you like to be added**:
Publish [ocm-cli image](https://github.com/open-component-model/ocm/pkgs/container/ocm%2Focm.software%2Focmcli%2Focmcli-image) also for `arm64` architecture.

**Why is this needed**:
The [ocm-cli binary](https://github.com/open-component-model/ocm/releases/tag/v0.15.0) itself is already published for `arm64`. By providing a corresponding oci-image as well, the life of people on `arm64` using ocm-cli in oci-images becomes much easier.

**Comment by mandelsoft** [comment]
I think, you mean darwin/arm64, because linux/arm64 is already handled.

**Comment by morri-son** [comment]
@zkdev did you pulled the latest or a valid release tag, e.g., v0.15.0? I just checked and saw that the latest version which gets created with each merge to the main branch, does not contain linux/arm64/v8 (Apple Silicon)

```
docker pull ghcr.io/open-component-model/ocm/ocm.software/ocmcli/ocmcli-image:latest
latest: Pulling from open-component-model/ocm/ocm.software/ocmcli/ocmcli-image
no matching manifest for linux/arm64/v8 in the manifest list entries
```

but the release versions does

```
docker pull ghcr.io/open-component-model/ocm/ocm.software/ocmcli/ocmcli-image:0.15.0
0.15.0: Pulling from open-component-model/ocm/ocm.software/ocmcli/ocmcli-image
63ca1fbb43ae: Pull complete
7a86a910904f: Pull complete
f3093e43c3dd: Pull complete
f72ebdd85a7c: Pull complete
Digest: sha256:e6959bc5f077f647881c5e7204b3e2a0effb527c361d0e0a2973f319a0432c72
Status: Downloaded newer image for ghcr.io/open-component-model/ocm/ocm.software/ocmcli/ocmcli-image:0.15.0
ghcr.io/open-component-model/ocm/ocm.software/ocmcli/ocmcli-image:0.15.0
```

@hilmarf, is it possible to publish the same architectures we do with the image created via the release action?

**Comment by zkdev** [comment]
@mandelsoft 
> I think, you mean darwin/arm64, because linux/arm64 is already handled.

I did not specify the os, because neither darwin nor linux seems to be supported.
I suggest to support both.

```
❯ docker manifest inspect ghcr.io/open-component-model/ocm/ocm.software/ocmcli/ocmcli-image:latest
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.oci.image.index.v1+json",
   "manifests": [
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 1050,
         "digest": "sha256:366aa5eb5c55fb0f2fd3354be1569f7d01eb2a04c0ade5c655a80b1d75c24e23",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 567,
         "digest": "sha256:5571faa5eecc35520a60444a0d415511bf63576f0d9c8a4a674d674714556658",
         "platform": {
            "architecture": "unknown",
            "os": "unknown"
         }
      }
   ]
}
```

**Comment by zkdev** [comment]
@morri-son I did pull latest

**Comment by morri-son** [comment]
yup, this is how 0.15.0 looks like 

```
docker manifest inspect ghcr.io/open-component-model/ocm/ocm.software/ocmcli/ocmcli-image:0.15.0
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.oci.image.index.v1+json",
   "manifests": [
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 954,
         "digest": "sha256:66500d6d12327a61c72fa8b4c69cfed629c5367779c91ff7169a54400bae366e",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 954,
         "digest": "sha256:9dcdf35b618ffb0278aa9c3fa070ebad2bcc18cc67ea148d0bb926dc85f1d746",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      }
   ]
}
```

**Comment by zkdev** [comment]
Okay I see, will use release tag instead - thank you!

---

On a side note, what is the `unknown` platform intended for?
Seems not to be spec compliant 🤔  https://github.com/opencontainers/image-spec/blob/main/image-index.md -> https://go.dev/doc/install/source#environment

**Comment by morri-son** [comment]
opened https://github.com/open-component-model/ocm-project/issues/291 as follow up, closing this.
