### ISSUE TITLE
Ensure that bigger (breaking) changes and potential breaking candidates are better and earlier communicated in the Release Notes

### ISSUE THREAD

**Issue by jakobmoellerdev** [open-component-model/ocm#995]
**What would you like to be added**:

- Add BREAKING notes on all potential candidates for PRs and allow manual editing of release notes and include that manual edit as MANDATORY process for every release
- Ensure that this goes hand in hand with release candidate creation (separate issue, TBD)

**Why is this needed**:

**Comment by hilmarf** [comment]
IMHO it's fine to generate the release notes as DRAFT, but publishing should be done only after HUMAN review and correction.

**Comment by jakobmoellerdev** [comment]
We now notify of breaking changes correctly and we have them via separate category in the release notes.
